 const swaggerDocument = {
    openapi :'3.0.1',
    info :{
        version:'1.0.0',
        title:'APIs Document',
        description:'This is a jobs api server where user can create his account , log in in his account and again create ,read ,delete, update his job(with authentication).It also has one publicRoute which does not need any authentication to create a job and that job will be a public job.',
        termsOfService: '',
        contact:{
            name:'Nandini panchal',
            email:'panchalnandini66@gmail.com',
        }

    },
    servers: [
        {
            url:'http://localhost:7000/api/v1',
            description:'Public Jobs server'
        },
        {
            url :'http://localhost:7000/api/v1/job',
            description:'Jobs server'
        },
        {
            url :'http://localhost:7000/api/v1/user',
            description:'User server'
        },

    ],
    components:{
        schemas:{

            User:{
                type:'object',
                properties:{
                    name:{
                        type:'string',
                        description:'Name of user',
                        example:'Neha pingale'
                    },
                    email:{
                        type:'string',
                        description:'Email ID of user',
                        example:'neha@example.com'
                    },
                    password:{
                        type:'string',
                        description:'Password for the account of user'
                    }
                }
            },
            Job:{
                type:'object',
                properties:{
                    company:{
                        type:'string',
                        description:'Name of the company',
                        exmaple:'TCS, wipro , Google , etc.'
                    },
                    position:{
                        type:'string',
                        description:'Job-role in that particular company',
                        example:'Sofware-developer , front-end developer , Data scientist'
                    },
                    status:{
                        type:'string',
                        description:'status of the job in particular company - Interview , Declined , Pending',
                        example:'Interview'
                    },
                    jobtype:{
                        type:'string',
                        description:'Whether the job will be private or public'
                    },
                    createdBy:{
                        type:'objectId',
                        description:'This field will be automatically generated by mongodb whenever a job will be created'
                    }
                }
            }
        }
    },
   
}

module.exports = swaggerDocument