 const swaggerDocument = {
    openapi :'3.0.1',
    info :{
        version:'1.0.0',
        title:'APIs Document',
        description:'This is a jobs api server where user can create his account , log in in his account and again create ,read ,delete, update his job(with authentication).It also has one publicRoute which does not need any authentication to create a job and that job will be a public job.',
        termsOfService: '',
        contact:{
            name:'Nandini panchal',
            email:'panchalnandini66@gmail.com',
        }

    },
    servers: [
        {
            url:'http://localhost:7000/api/v1',
            description:'Public Jobs server'
        },
        {
            url :'http://localhost:7000/api/v1/job',
            description:'Jobs server'
        },
        {
            url :'http://localhost:7000/api/v1/user',
            description:'User server'
        },

    ],
    components:{
        schemas:{

            User:{
                type:'object',
                properties:{
                    name:{
                        type:'string',
                        description:'Name of user',
                        example:'Neha pingale'
                    },
                    email:{
                        type:'string',
                        description:'Email ID of user',
                        example:'neha@example.com'
                    },
                    password:{
                        type:'string',
                        description:'Password for the account of user'
                    }
                }
            },
            Job:{
                type:'object',
                properties:{
                    company:{
                        type:'string',
                        description:'Name of the company',
                        exmaple:'TCS, wipro , Google , etc.'
                    },
                    position:{
                        type:'string',
                        description:'Job-role in that particular company',
                        example:'Sofware-developer , front-end developer , Data scientist'
                    },
                    status:{
                        type:'string',
                        description:'status of the job in particular company - Interview , Declined , Pending',
                        example:'Interview'
                    },
                    jobtype:{
                        type:'string',
                        description:'Whether the job will be private or public'
                    },
                    createdBy:{
                        type:'objectId',
                        description:'This field will be automatically generated by mongodb whenever a job will be created'
                    }
                }
            }
        },
       
       
    },
    paths:{
        '/job':{
            'get':{
                summary:'Returns the jobs of user',
                responses:{
                    200:{
                        description:'List of jobs of user',
                        'content':{
                            'application/json':{
                                schema:{
                                    type:'array',
                                    items:{
                                        id:{
                                            type:'string',
                                            description:'ID of the job'
                                        },
                                        company:{
                                            type:'string',
                                            description:'company name'
                                        },
                                        position:{
                                            type:'string',
                                            description:'job role'
                                        },
                                        status:{
                                            type:'string',
                                            description:'status of job'
                                        },
                                        jobtype:{
                                            type:'string',
                                            description:'Jobtype-Public/Private'
                                        },
                                        createdBy:{
                                            type:'object',
                                            description:'Id of the user'
                                        },
                                        createdAt:{
                                            type:'object',
                                            description:'Time at when the job is created'
                                        },
                                        
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        '/':{
            'get':{
                summary:'Returns the public jobs',
                responses:{
                    200:{
                        description:'List of public jobs',
                        'content':{
                            'application/json':{
                                schema:{
                                    type:'array',
                                    items:{
                                        id:{
                                            type:'string',
                                            description:'ID of the job'
                                        },
                                        company:{
                                            type:'string',
                                            description:'company name'
                                        },
                                        position:{
                                            type:'string',
                                            description:'job role'
                                        },
                                        status:{
                                            type:'string',
                                            description:'status of job'
                                        },
                                        jobtype:{
                                            type:'string',
                                            description:'Jobtype-Public/Private'
                                        },
                                        createdBy:{
                                            type:'object',
                                            description:'Id of the user'
                                        },
                                        createdAt:{
                                            type:'object',
                                            description:'Time at when the job is created'
                                        },
                                        
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },
}

module.exports = swaggerDocument